// Sitemate SM errors
export enum ErrorEnum {
    SM_INTERNAL_SERVER_ERROR = "SM_INTERNAL_SERVER_ERROR",
    SM_INVALID_SIGNATURE = "SM_INVALID_SIGNATURE",
    SM_NOT_FOUND = "SM_NOT_FOUND",
    SM_DUPLICATE_KEY = "SM_DUPLICATE_KEY",
}
